### Get all posts (response includes author info)
GET http://localhost:1338/posts
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFsaWNlIiwic3ViIjoxLCJpYXQiOjE3NTQ2NjI4MTMsImV4cCI6MTc1NDY2NjQxM30.0Nhv9_iNKSlvyEPIZLlEacdT4IX1I6Ypb3RI5c9VRE8

# The returned posts will include the author object with minimal info (id, username, etc.)

### Get a specific post by id (response includes author info)
GET http://localhost:1338/posts/1
Accept: application/json

### Create a new post (author is set automatically from the logged-in user)
POST http://localhost:1338/posts
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFsaWNlIiwic3ViIjoxLCJpYXQiOjE3NTQ2NjI4MTMsImV4cCI6MTc1NDY2NjQxM30.0Nhv9_iNKSlvyEPIZLlEacdT4IX1I6Ypb3RI5c9VRE8

{
  "title": "My First Post",
  "content": "This is the content"
}

### Update a post
PATCH http://localhost:1338/posts/7
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFsaWNlIiwic3ViIjoxLCJpYXQiOjE3NTQ2NjI4MTMsImV4cCI6MTc1NDY2NjQxM30.0Nhv9_iNKSlvyEPIZLlEacdT4IX1I6Ypb3RI5c9VRE8

{
  "id": 1,
  "title": "Updated title"
}

### Delete a post
DELETE http://localhost:1338/posts/6
